networks:
  beanjournal_network:

volumes:
  sqlvolume:
  redisvolume:

services:
  beanjournal.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: beanjournal.database
    volumes:
      - sqlvolume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Soybean2610@
      - MSSQL_PID=Express
    networks:
      - beanjournal_network

  beanjournal.api:
    image: ${DOCKER_REGISTRY-}beanjournalbackend
    container_name: beanjournal.api
    build:
      context: .
      dockerfile: BeanJournal_BackEnd/Dockerfile
    depends_on:
      - beanjournal.database
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - beanjournal_network

  beanjournal.cache:
    image: redis:latest
    container_name: beanjournal.cache
    restart: always
    volumes:
      - redisvolume:/data
    ports:
      - "6379:6379" 
    networks:
      - beanjournal_network
